package com.rentmanager.shared.exception;

public enum ErrorCode {

    // Generic
    INTERNAL_ERROR,
    BUSINESS_ERROR,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,

    // Unit module
    UNIT_OCCUPIED,
    UNIT_NOT_FOUND,
    UNIT_INACTIVE,

    // Lease module
    LEASE_ALREADY_ACTIVE,
    LEASE_NOT_ACTIVE,
    INVALID_LEASE_STATE,
    LEASE_NOT_FOUND,
    LEASE_TENANT_NULL,
    LEASE_PROPERTY_NULL,
    LEASE_UNIT_NULL,
    LEASE_PROFILE_NULL,
    LEASE_NUMBER_BLANK,
    LEASE_INVALID_RENT,
    LEASE_INVALID_DEPOSIT,
    LEASE_INVALID_DATE_RANGE,
    LEASE_APPROVAL_ONLY_DRAFT_ALLOWED,
    LEASE_ACTIVATION_ONLY_PENDING_APPROVAL_ALLOWED,
    LEASE_REJECTION_ONLY_DRAFT_OR_PENDING_ALLOWED,
    LEASE_TERMINATION_ONLY_ACTIVE_ALLOWED,
    LEASE_TERMINATION_TYPE_REQUIRED,
    LEASE_TERMINATION_REASON_REQUIRED,
    LEASE_TERMINATION_ACTOR_REQUIRED,
    LEASE_TERMINATION_TENANT_REQUIRED,
    LEASE_EXPIRATION_ONLY_ACTIVE_ALLOWED,
    LEASE_EXPIRATION_NOT_APPLICABLE_TO_MONTH_TO_MONTH,
    LEASE_RENEWAL_ONLY_ACTIVE_OR_EXPIRED_ALLOWED,
    LEASE_RENEWAL_START_DATE_REQUIRED,
    LEASE_RENEWAL_END_DATE_REQUIRED,
    LEASE_RENEWAL_INVALID_DATE_RANGE,
    LEASE_RENEWAL_TENANT_REQUIRED,
    LEASE_RENEWAL_ACTOR_REQUIRED,
    LEASE_UPDATE_CLOSED_NOT_ALLOWED,
    LEASE_UPDATE_INVALID_DATE_RANGE,
    LEASE_AMOUNT_REQUIRED,
    LEASE_AMOUNT_MUST_BE_NON_NEGATIVE,
    ACCESS_DENIED,
    UNAUTHORIZED,
    FORBIDDEN,


    // Property module
    PROPERTY_NOT_FOUND,
    PROPERTY_INACTIVE,

    // Security / tenancy
    UNAUTHORIZED_ACCESS,
    TENANT_MISMATCH,




    // Lease module — add these two
    LEASE_AWAITING_DEPOSIT_ONLY_PENDING_ALLOWED,

    LEASE_ACTIVATION_ONLY_AWAITING_DEPOSIT_ALLOWED,
    LEASE_ACTIVATION_ONLY_PENDING_ACTIVATION_ALLOWED,



    // Deposit module — new section
    DEPOSIT_AMOUNT_REQUIRED,
    DEPOSIT_TENANT_PROFILE_NULL,
    DEPOSIT_LEASE_NULL,
    DEPOSIT_UNIT_NULL,
    DEPOSIT_ALREADY_PAID,
    DEPOSIT_PAYMENT_INSUFFICIENT,
    DEPOSIT_NOT_HELD,
    DEPOSIT_REFUND_EXCEEDS_PAID,
    DEPOSIT_NOT_FOUND,


    // --- Lease validation ---
    LEASE_TYPE_REQUIRED,
    LEASE_BILLING_CYCLE_REQUIRED,
    LEASE_START_DATE_IN_PAST,
    LEASE_PROPERTY_NOT_FOUND,
    LEASE_PROFILE_NOT_FOUND,
    LEASE_UNIT_ALREADY_LEASED,

    // Rent ledger module — new section
    RENT_TRANSACTION_TENANT_NULL,
    RENT_TRANSACTION_LEDGER_ENTRY_NULL,
    RENT_TRANSACTION_LEASE_NULL,
    RENT_TRANSACTION_TYPE_NULL,
    RENT_TRANSACTION_INVALID_AMOUNT,
    RENT_TRANSACTION_SOURCE_NULL,
    RENT_TRANSACTION_RECORDED_BY_REQUIRED,
    RENT_TRANSACTION_OCCURRED_AT_NULL,

    RENT_LEDGER_ENTRY_TENANT_NULL,
    RENT_LEDGER_ENTRY_LEASE_NULL,
    RENT_LEDGER_ENTRY_UNIT_NULL,
    RENT_LEDGER_ENTRY_TENANT_PROFILE_NULL,
    RENT_LEDGER_ENTRY_PERIOD_NULL,
    RENT_LEDGER_ENTRY_PERIOD_INVALID,
    RENT_LEDGER_ENTRY_DUE_DATE_NULL,
    RENT_LEDGER_ENTRY_INVALID_AMOUNT_DUE,
    RENT_LEDGER_ENTRY_UNSUPPORTED_TRANSACTION_TYPE,
    RENT_LEDGER_ENTRY_INVALID_ADJUSTMENT,
    RENT_LEDGER_ENTRY_ILLEGAL_TRANSITION,
    RENT_LEDGER_ENTRY_INVALID_DAYS_OVERDUE,
    RENT_LEDGER_ENTRY_INVALID_REFUND_AMOUNT,
    RENT_LEDGER_ENTRY_ALREADY_SETTLED,
    RENT_LEDGER_ENTRY_REQUIRES_RESOLUTION,
    RENT_LEDGER_ENTRY_TRANSACTION_NULL,
    RENT_LEDGER_ENTRY_TRANSACTION_MISMATCH,


    RENT_LEDGER_ENTRY_NOT_FOUND,
}