version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: rentmanager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentmanager
      POSTGRES_USER: rentmanager
      POSTGRES_PASSWORD: rentmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rentmanager-network

  redis:
    image: redis:7
    container_name: rentmanager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rentmanager-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: rentmanager-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - rentmanager-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: rentmanager-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - rentmanager-network

volumes:
  pgdata:

networks:
  rentmanager-network:
    driver: bridge