spring:
  application:
    name: rentmanager-backend

  profiles:
    active: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rentmanager}
    username: ${DB_USERNAME:rentmanager}
    password: ${DB_PASSWORD:rentmanager}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://social-monitor-54.clerk.accounts.dev/.well-known/jwks.json




flyway:
  enabled: true
  locations: classpath:db/migration
  out-of-order: false



server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

application:
  security:
    issuer: ${JWT_ISSUER:rentmanager-backend}
    jwtSecret: ${JWT_SECRET:dev-secret-change-me}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION:3600s}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION:86400s}
    bcryptStrength: ${BCRYPT_STRENGTH:12}
    enableHttpsOnlyCookies: true
    enableSecureHeaders: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}



daraja:
  consumer-key: ${DARAJA_CONSUMER_KEY:YOUR_CONSUMER_KEY}
  consumer-secret: ${DARAJA_CONSUMER_SECRET:YOUR_CONSUMER_SECRET}
  business-short-code: ${DARAJA_SHORT_CODE:174379}
  passkey: ${DARAJA_PASSKEY:YOUR_DARAJA_PASSKEY}
  callback-url: ${DARAJA_CALLBACK_URL:https://yourdomain.com/api/v1/public/reservations/mpesa/callback/YOUR_CALLBACK_SECRET}
  base-url: ${DARAJA_BASE_URL:https://sandbox.safaricom.co.ke}
  callback-secret: ${DARAJA_CALLBACK_SECRET}
  credentials-encryption-key: ${DARAJA_CREDENTIALS_ENCRYPTION_KEY}




clerk:
  secret-key: ${CLERK_SECRET_KEY:YOUR_CLERK_SECRET_KEY}
  base-url: https://api.clerk.com/v1



africastalking:
  enabled: ${AT_ENABLED:false}
  api-key: ${AT_API_KEY:YOUR_AT_API_KEY}
  username: ${AT_USERNAME:sandbox}
  sender-id: ${AT_SENDER_ID:}
  base-url: ${AT_BASE_URL:https://api.sandbox.africastalking.com/version1/messaging}