#!/usr/bin/env bash
# Generate the secrets this deployment needs. Run it once, on your own machine,
# and put each value straight into your password manager.
#
#   ./gen-secrets.sh
set -euo pipefail

echo "Save every line below in your password manager BEFORE closing this window."
echo
echo "DARAJA_CREDENTIALS_ENCRYPTION_KEY (Render)"
echo "  $(openssl rand -base64 32)"
echo "  Encrypts landlords' M-Pesa credentials. If this is lost, their stored"
echo "  credentials can never be read again. It must never change."
echo
echo "BACKUP_PASSPHRASE (GitHub Actions secret)"
echo "  $(openssl rand -hex 32)"
echo "  Encrypts the nightly database backups. Lose it and no backup can be"
echo "  restored."
echo
echo "JWT_SECRET is generated by Render itself (render.yaml) — nothing to do."
